### ISSUE TITLE
ERROR in ./~/css-loader!./src/index.js Module build failed: Unknown word (1:1)

### ISSUE THREAD

**Issue by PetalsOnaWet** [luckykun/About-React#4]
我没有clone你的代码，按照你的代码手动敲了一份webpack.config。然后我发现无论我入口文件写什么运行webpack的时候都会报
```
ERROR in ./~/css-loader!./src/index.js
Module build failed: Unknown word (1:1)
```
这个错误。请问我应该怎么解决它？我尝试搜索了下，没能找到答案。

**Comment by luckykun** [comment]
`css-loader`的问题吧

**Comment by langrren** [comment]
大哥。。。

**Comment by PetalsOnaWet** [comment]
大哥。。我不知道该回复什么

**Comment by luckykun** [comment]
你把代码贴上来看看

**Comment by PetalsOnaWet** [comment]
webpack.config.js的代码

> var path = require('path');
> module.exports = {
> 	entry: [
> 		"./src/index.js"
> 	],
> 	output:{
> 		path: './dist/',
> 		filename: 'bundle.js'
> 	},
> 	module:{
> 		loaders:[
> 			{ test: /\.js$/, loader: 'jsx!babel',include: /src/},
> 			{ tset: /\.css$/, loader: 'style!css'},
> 			{ test: /\.scss$/, loader: 'style!css!sass' },
> 			{ test: /\.(png|jpg)$/, loader: 'ur?limit=8192' }
> 		]
> 	}
> }

index.js的代码


>  'use strict';
> // 引入样式表
> require('./styles/main.scss');
> 
> // 引入组件
> require('./components/App');

**Comment by PetalsOnaWet** [comment]
和你的代码没差别。估计是本地环境出问题了

**Comment by luckykun** [comment]
那估计因该是版本问题。
那你就把我的clone下来看能不能运行，如果能，就说明是某个插件的版本问题。
